---
title: "DataManipulation"
author: "Xuehan Yang"
date: "2021/10/2"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Data

```{r, warning=FALSE}
library(tidyverse)

options(tibble.print_min = 3)

litters_data = read_csv("./data/FAS_litters.csv", col_types = "ccddiiii")
litters_data = janitor::clean_names(litters_data)

pups_data = read_csv("./data/FAS_pups.csv", col_types = "ciiiii")
pups_data = janitor::clean_names(pups_data)
```


# Select

```{r}
select(litters_data, group, litter_number, gd0_weight, pups_born_alive)

select(litters_data, group:gd_of_birth)

select(litters_data, -pups_survive)

select(litters_data, GROUP = group, LITTER_NUMBER = litter_number)

rename(litters_data, GROUP= group, LiTtEr_NuMbEr = litter_number)

select(litters_data, starts_with("gd"))

select(litters_data, litter_number, pups_survive, everything())

relocate(litters_data, litter_number, pups_survive)
```

# Filter

```{r}
drop_na(litters_data, gd18_weight)
```

# Mutate

```{r}
mutate(litters_data,
       wt_gain = gd18_weight - gd0_weight,
       group = str_to_lower(group))
```

# Arrange

```{r}
head(arrange(litters_data, group, pups_born_alive), 10)
```

# %>% 

```{r}
litters_data = 
  read_csv("./data/FAS_litters.csv", col_types = "ccddiiii") %>%
  janitor::clean_names() %>%
  select(-pups_survive) %>%
  mutate(
    wt_gain = gd18_weight - gd0_weight,
    group = str_to_lower(group)) %>% 
  drop_na(wt_gain)

litters_data
```

```{r}
litters_data = 
  read_csv("./data/FAS_litters.csv", col_types = "ccddiiii") %>%
  janitor::clean_names(dat = .) %>%
  select(.data = ., -pups_survive) %>%
  mutate(.data = .,
    wt_gain = gd18_weight - gd0_weight,
    group = str_to_lower(group)) %>% 
  drop_na(data = ., wt_gain)
```

```{r}
litters_data %>% 
  lm(wt_gain~pups_born_alive, data = .) %>% 
  broom::tidy()
```










