---
title: "Simple document"
output: github_document
---

I'm an R Markdown document! 

```{r, message=FALSE}
library(tidyverse)
```


# Paths

Using relative Path to load data.

# Importing data tables

```{r, warning=FALSE}
litters_data =  read_csv(file = "./data/FAS_litters.csv") %>% 
  janitor::clean_names()

names(litters_data)
```

Assessment: import pups.

```{r}
pups_data = read_csv(file = "./data/FAS_pups.csv") %>% janitor::clean_names()

```

# Looking at data

```{r}
litters_data

tail(litters_data)

skimr::skim(litters_data)

view(litters_data)
```

#Argumetns to read_*

```{r}
litters_data = read_csv(file = "./data/FAS_litters.csv", skip = 10, col_names = FALSE)
```

# Parsing columns

```{r}
litters_data = read_csv(file = "./data/FAS_litters.csv", col_types = cols(
  Group = col_character(),
  `Litter Number` = col_character(),
  `GDO weight` = col_double(),
  `GD18 weight` = col_double(),
  `GD of Birth` = col_integer(),
  `Pups born alive` = col_integer(),
  `Pups dead @ birth` = col_integer(),
  `Pups survive` = col_integer())
  )

tail(litters_data)
```

Parsing using a shorthand for every data type.

```{r}
litters_data = read_csv(file = "./data/FAS_litters.csv", col_types = "ccddiiii")
```

#Other file formats

```{r}
library(readxl)

mlb11_data = read_excel("./data/mlb11.xlsx", n_max = 20)
head(mlb11_data, 5)
```


```{r}
library(haven)

pulse_data = read_sas("./data/public_pulse_data.sas7bdat")

head(pulse_data, 5)
```






















